Back side logic for chat functionality initialized
WildCodeSchool/2020-11-wns-remote2-groupe4-projet pull request #22
Opened 2021-02-05 17:03 UTC by Code-Hello

Channel and message logic added
Subscription initialized

2021-02-14 16:00 UTC, lebowvsky approved these changes

2021-03-03 14:56 UTC, arnaudrenaud requested changes
Bon travail ! Mais à l'avenir essayez de découper les tâches en plus petites unités pour que les PR puissent sortir plus vite et donc être relues plus vite.

2021-03-03 14:56 UTC, arnaudrenaud commented on src/resolvers/ChannelResolver.ts
> +  async channelUsers(@Arg('id') id: string): Promise<AppUser[] | undefined> {
Est-on obligé d'avoir une Query spécifiquement pour avoir les utilisateurs d'un canal ?

L'intérêt de GraphQL est justement de pouvoir accéder sur demande aux données imbriquées, en l'occurence les utilisateurs à l'intérieur d'un canal – par exemple :
```
channel(id: "1234") {
  users {
    id
  }
}
```

2021-03-03 14:56 UTC, arnaudrenaud commented on src/resolvers/ChannelResolver.ts
> +  async channelMessages(@Arg('id') id: string): Promise<Message[] | undefined> {
Même remarque que pour `channelUsers`.

2021-03-03 14:56 UTC, arnaudrenaud commented on src/inputs/MessageInput.ts
> +  authorId!: string;
Cela veut dire qu'un utilisateur A peut créer un message ayant pour auteur B ? Je retirerais cet attribut et j'utiliserais plutôt l'utilisateur authentifié comme auteur du message.

2021-03-03 14:56 UTC, arnaudrenaud commented on src/resolvers/MessageResolver.ts
> +      const user = await AppUser.findOne(data.authorId);
Plus besoin de cette instruction si on utilise l'utilisateur authentifié comme auteur.

2021-03-03 14:56 UTC, arnaudrenaud commented on src/resolvers/MessageResolver.ts
> +      throw new Error('No messages for this user on this channel.');
Pas la peine de gérer ce cas : s'il n'y a pas de messages, on retournera un tableau vide mais ça ne constitue pas une erreur.

2021-03-03 14:56 UTC, arnaudrenaud commented on src/resolvers/MessageResolver.ts
> +      throw new Error('No messages for this user.');
Pas la peine de gérer ce cas : s'il n'y a pas de messages, on retournera un tableau vide mais ça ne constitue pas une erreur.

2021-03-03 14:56 UTC, arnaudrenaud commented on src/resolvers/MessageResolver.ts
> +      throw new Error('No messages for this channel.');
Pas la peine de gérer ce cas : s'il n'y a pas de messages, on retournera un tableau vide mais ça ne constitue pas une erreur.

2021-03-04 09:35 UTC, Code-Hello commented on src/resolvers/ChannelResolver.ts
> +  async channelUsers(@Arg('id') id: string): Promise<AppUser[] | undefined> {
Effectivement

2021-03-04 09:41 UTC, merged